### PR TITLE
129 refactor playlistcontrols to edit uploaded playlists

### LINKED ISSUE #129: Refactor PlaylistControls to Edit Uploaded Playlists

### PR DESCRIPTION
**Pull request by Ernest0G**
## Changes
_List Changes Introduced by this PR_
1. Added ability to edit the name, cover image, and add songs in the playlist editor.
2. Added ability to delete a track from an uploaded playlist.
3. Added ability to delete an uploaded playlist. 

## Purpose
Previously, there wasn't a way to edit or remove a playlist that was uploaded. 

## Approach
These changes provides all the functionality needed to have control over the playlist. 

## Current Issues
1. Uploading a playlist takes a while. Maybe having a progress bar to signify when its done would help let the user know.
2. Library needs to be updated as soon as the changes have been implemented on MongoDB and Amazon S3.
3. CORS issue with some songs sometimes.

_If this closes an issue, reference the issue here. If it doesn't, remove this line_
Closes #129

### CODE REVIEW

**Review by tkgonzal — APPROVED** [review]
(praise/question): Looks good ! Regarding the CORS issues, would you happen to know the specific error/warning message that pops up in the console when they occur? There was a similar problem that we debugged earlier and I was wondering if it might be related.

**Comment by Ernest0G** [comment]
The specific error with CORS is: 
Access to video at 'https://bvt-music-player.s3.us-west-1.amazonaws.com/nlMwpsV00xrtQ0NEftGw' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
I tried many things in terms of setting the CORS policy on Amazon S3 but nothing seemed to work. What's odd is it will only throw that error for one song, usually the first song in the playlist.
@tkgonzal

**Comment by tkgonzal** [comment]
@Ernest0G Ohh bet I think I know what's going on then. When the ReactPlayer component starts up it doesn't have the "crossorigin" attribute at start since its an outside module so we have to assign it manually. So I think when it starts up, it makes an initial request for the resource without the CORS headers, but then after it gets assigned its able to pull the resource. Is it affecting any of the functionality with playback or playlist editing? Cause if not I think we should be fine with it popping up

**Comment by Ernest0G** [comment]
@tkgonzal Some times there will be multiple songs that create the CORS issue but will play after selecting a different song or playlist first. The first song in the playlist with the CORS issue seems to be the one that won't play at all.

**Comment by tkgonzal** [comment]
@Ernest0G Oh dang that is a problem. I pulled from you branch to try and replicate the error but I don't seem to be getting it. It's only occuring when you select the first song on a local playlist right?

**Comment by tkgonzal** [comment]
(note): Ernesto and I DM'ed a bit to debug the CORS issue and discovered it seems to be a Chrome specific bug. We came up with a thought on how to deal with it, I'm going to make an issue for it right now and I'll try to get around to working on it either tomorrow or Monday.

**Review by missile720 — APPROVED** [review]
(praise): Looks good!

**Pull request merged**
